spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=g4ecfbb775fd1ef_dblab_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ss230101
    password: Spring_94527


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database:oracle
# Initial Data config
defer-datasource-initialization: true